context("acquire")

test_that("Data types", {
   shots <- acquire()
   expect_true(dim(shots)[1] > 1)
   rebounds <- acquire("rebound")
   expect_true(dim(rebounds)[1] > 1)
   pass_dash <- acquire("pass")
   expect_true(dim(pass_dash)[1] > 1)
   defense_dash <- acquire("shotdefend")
   expect_true(dim(defense_dash)[1] > 1)
   reb_dash <- acquire("reb")
   expect_true(dim(reb_dash)[1] > 1)
   shot_dash <- acquire("shots")
   expect_true(dim(shot_dash)[1] > 1)
})